image: gcr.io/google.com/cloudsdktool/cloud-sdk

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv-py3/

before_script:
  - python -V  # Print out python version for debugging
  - python3 -m venv venv-py3
  - source venv-py3/bin/activate
  - pip install -U -r requirements.txt

test:
  script:
    - pycodestyle main.py
