application: zrcal-leinen
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: lxml
  version: 2.3

handlers:
- url: /(favicon.ico)
  static_files: static/images/\1
  mime_type: image/vnd.microsoft.icon
  upload: static/images/(.*)

- url: /.*
  script: zrcal.app
