runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: setuptools
  version: "36.6.0"
- name: pytz
  version: "2017.3"
- name: webapp2
  version: "2.5.2"
- name: grpcio
  version: 1.0.0

handlers:
- url: /(favicon.ico)
  static_files: static/images/\1
  mime_type: image/vnd.microsoft.icon
  upload: static/images/(.*)

- url: /css
  static_dir: css

- url: /robots.txt
  static_files: static/robots.txt
  mime_type: text/plain
  upload: static/robots.txt

- url: /.*
  script: main.app

env_variables:
  DJANGO_SETTINGS_MODULE: 'settings'
