runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: six
  version: "1.9.0"
- name: lxml
  version: "3.7.3"
- name: setuptools
  version: "0.6c11"
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.23"
- name: django
  version: "1.11"
- name: pytz
  version: "2017.2"

handlers:
- url: /(favicon.ico)
  static_files: static/images/\1
  mime_type: image/vnd.microsoft.icon
  upload: static/images/(.*)

- url: /css
  static_dir: css

- url: /.*
  script: zrcal.app

env_variables:
  DJANGO_SETTINGS_MODULE: 'settings'
